image: node:10

cache:
  paths:
    - node_modules/
    - .yarn/

stages:
  - test

before_script:
  - node -v
  - npm -v
  - yarn -v
  - yarn --pure-lockfile --cache-folder .yarn

build-and-test:
  stage: test
  script:
    - yarn run build
    - yarn run lint
    - yarn run test

