# Using https://github.com/marketplace/actions/deploy-to-github-pages
# See also https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
name: Build the docs

on: [push]

defaults:
  run:
    working-directory: docs

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate the documentation
      run: docker run --rm -v $(pwd):/src --entrypoint /bin/sh klakegg/hugo:0.74.3-ext-alpine .docker-build-documentation.sh
