# https://github.com/actions/setup-node
name: Build and test the Nash Link Node.js SDK

on: [push]

defaults:
  run:
    working-directory: sdk-node-typescript

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --pure-lockfile
    - run: yarn run build
    - run: yarn run lint
    - run: yarn run test
